[package]
name = "logsmith-app"
version = "0.1.0"
authors = ["Ricki Hastings <rickihastings22@gmail.com>"]
edition = "2018"
license = "GNU General Public License v3.0"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
dlopen = "0.1.6"
dlopen_derive = "0.1.3"
