[package]
name = "input-stdin"
version = "0.1.0"
authors = ["Ricki Hastings <rickihastings22@gmail.com>"]
edition = "2018"
license = "GNU General Public License v3.0"

[dependencies]
config = { path = "../../packages/config" }

[lib]
crate-type = ["dylib"]
